version: '2'
services:
  postfix:
    image: docker-postfix:local
    #expose:
    #- 25
    ports:
    - 25:25
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
