version: '2'
services:
  postfix:
    image: ghcr.io/jr0w3/docker-postfix:latest
    expose:
    - 25
    ports:
    - 25:25
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
